"""Application config — single source of truth for env vars.

PRD §7: `setup.sh` wizard writes `.env`; this module loads it.
Secrets are wrapped in `SecretStr` so they never leak into logs or repr.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

from pydantic import Field, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def _blank_to_none(value: Any) -> Any:
    """Treat empty / whitespace-only strings as unset.

    Heroku and many cloud env stores cannot distinguish "key absent" from
    "key present but empty"; both surface as ``""``. Default pydantic
    coercion then rejects ``""`` for ``int | None`` / ``Path | None`` fields
    even though the documented intent is "leave it unset for receive-only".
    """
    if isinstance(value, str) and value.strip() == "":
        return None
    return value


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="OPENBOT_",
        extra="ignore",
        frozen=True,
    )

    # ─── GitHub App webhook (PRD §5.1: verify signature is the trust boundary) ───
    github_webhook_secret: SecretStr | None = Field(
        default=None,
        description=(
            "HMAC-SHA-256 secret set when creating the GitHub App. "
            "If unset, /webhook/github responds 503 — webhooks are intentionally "
            "off until the wizard has run."
        ),
    )

    # ─── GitHub App identity (PRD §13 #5: per-user-built App) ───
    # Both must be set for write-back (reply / labels / role) to work.
    # Receive-only deployments (verify + parse only) can leave them unset.
    github_app_id: int | None = Field(
        default=None,
        description="Numeric App ID from the GitHub App settings page.",
    )
    github_app_private_key_path: Path | None = Field(
        default=None,
        description=(
            "Path to the App's PEM-encoded private key. "
            "Generated by `setup.sh`; commonly `./secrets/github-app-private.pem`. "
            "On ephemeral hosts (Heroku/Render) prefer `github_app_private_key_pem`."
        ),
    )
    # Inline PEM source — used on hosts with no persistent filesystem (Heroku,
    # Render, Fly machines without volumes). When both pem and path are set,
    # pem wins so deploys can roll forward without touching the .env path.
    github_app_private_key_pem: SecretStr | None = Field(
        default=None,
        description=(
            "PEM-encoded private key as a literal string (begins with "
            "'-----BEGIN'). Set this in env-var-only deploys (Heroku: "
            '`heroku config:set OPENBOT_GITHUB_APP_PRIVATE_KEY_PEM="$(cat key.pem)"`).'
        ),
    )

    # ─── Persistence ───
    # If unset, webhook dedup falls open (logs WARNING). Production MUST set it.
    redis_url: str | None = Field(
        default=None,
        description=(
            "Redis connection URL, e.g. redis://localhost:6379/0. "
            "Used for webhook dedup (now); rate-limit counters and the "
            "workflow queue land in the middleware slice."
        ),
    )
    # If unset, cost_meter / audit_log are not persisted. LLM workflows still
    # run, but PRD §4.5 budget caps + §9.4 audit cannot be enforced.
    postgres_url: str | None = Field(
        default=None,
        description=(
            "Postgres URL using the asyncpg driver, e.g. "
            "postgresql+asyncpg://openbot:openbot@localhost:5432/openbot. "
            "Required for cost tracking + audit log."
        ),
    )

    # ─── Worker queue (PRD §5.1 / harness spec §9.3) ───
    # Single-process worker with N asyncio consumers. v0.1 defaults to
    # 4 — fine for individual maintainer scale (<10 events/day). At
    # higher load: start more `python -m openbot.queue.runner` processes;
    # they share the same Redis consumer group.
    worker_concurrency: int = Field(
        default=4,
        ge=1,
        le=64,
        description=(
            "Number of asyncio consumer tasks per worker process. "
            "Each task pulls from openbot:workflows independently."
        ),
    )

    debug: bool = Field(default=False, description="Verbose logs; never enable in production.")

    # ─── Debug echo (state-machine slice) ───
    # Routes every classified webhook to the debug echo handler — see
    # ``openbot.handlers.debug_echo``. Default ``True`` so the
    # initial state-machine slice has visible end-to-end output before
    # real workflow logic lands. Flip to ``False`` once triage/review/fix/
    # chat handlers are wired through real LLM calls (PRD section 4.1 to 4.4).
    debug_echo_enabled: bool = Field(
        default=True,
        description=(
            "When True, all classified webhooks are routed to the "
            "debug_echo handler instead of the real workflow stubs. "
            "Useful for verifying the state-machine pipeline end-to-end "
            "before agent logic lands."
        ),
    )

    # ─── Observability ───
    # Sentry is opt-in cross-cutting exception capture. Domain events
    # (workflow STARTED / COMPLETED / SKIPPED) stay in audit_log; Sentry
    # only sees uncaught exceptions and httpx 5xx so the on-call view
    # isn't swamped by routine SKIPPED rows.
    sentry_dsn: SecretStr | None = Field(
        default=None,
        description=(
            "Sentry DSN. When unset, sentry_sdk.init(dsn=None) is a "
            "documented no-op — local dev and CI keep working unchanged."
        ),
    )
    # Tags every Sentry event so prod errors don't mix with dev / preview.
    # Heroku sets this via `heroku config:set OPENBOT_ENVIRONMENT=production`.
    environment: str = Field(
        default="development",
        description="Environment tag attached to Sentry events.",
    )
    # 0.0 = error-only (cheapest tier). Bump to 0.05-0.2 once you have
    # the Sentry Performance budget to spare. Keep <1.0 or you'll burn
    # the free-tier event budget on the first traffic spike.
    sentry_traces_sample_rate: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Fraction of transactions sent to Sentry Performance.",
    )

    # ── Coerce "" → None for optional non-string fields ──
    # Applied at `mode='before'` so it runs ahead of int / Path validation.
    _blank_to_none = field_validator(
        "github_app_id",
        "github_app_private_key_path",
        "redis_url",
        "postgres_url",
        mode="before",
    )(staticmethod(_blank_to_none))


@lru_cache
def get_settings() -> Settings:
    """Cached accessor. Tests call `get_settings.cache_clear()` after monkeypatching env."""
    return Settings()
