"""Application config — single source of truth for env vars.

PRD §7: `setup.sh` wizard writes `.env`; this module loads it.
Secrets are wrapped in `SecretStr` so they never leak into logs or repr.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="OPENBOT_",
        extra="ignore",
        frozen=True,
    )

    # ─── GitHub App webhook (PRD §5.1: verify signature is the trust boundary) ───
    github_webhook_secret: SecretStr | None = Field(
        default=None,
        description=(
            "HMAC-SHA-256 secret set when creating the GitHub App. "
            "If unset, /webhook/github responds 503 — webhooks are intentionally "
            "off until the wizard has run."
        ),
    )

    # ─── GitHub App identity (PRD §13 #5: per-user-built App) ───
    # Both must be set for write-back (reply / labels / role) to work.
    # Receive-only deployments (verify + parse only) can leave them unset.
    github_app_id: int | None = Field(
        default=None,
        description="Numeric App ID from the GitHub App settings page.",
    )
    github_app_private_key_path: Path | None = Field(
        default=None,
        description=(
            "Path to the App's PEM-encoded private key. "
            "Generated by `setup.sh`; commonly `./secrets/github-app-private.pem`. "
            "On ephemeral hosts (Heroku/Render) prefer `github_app_private_key_pem`."
        ),
    )
    # Inline PEM source — used on hosts with no persistent filesystem (Heroku,
    # Render, Fly machines without volumes). When both pem and path are set,
    # pem wins so deploys can roll forward without touching the .env path.
    github_app_private_key_pem: SecretStr | None = Field(
        default=None,
        description=(
            "PEM-encoded private key as a literal string (begins with "
            "'-----BEGIN'). Set this in env-var-only deploys (Heroku: "
            '`heroku config:set OPENBOT_GITHUB_APP_PRIVATE_KEY_PEM="$(cat key.pem)"`).'
        ),
    )

    # ─── Persistence ───
    # If unset, webhook dedup falls open (logs WARNING). Production MUST set it.
    redis_url: str | None = Field(
        default=None,
        description=(
            "Redis connection URL, e.g. redis://localhost:6379/0. "
            "Used for webhook dedup (now); rate-limit counters and the "
            "workflow queue land in the middleware slice."
        ),
    )
    # If unset, cost_meter / audit_log are not persisted. LLM workflows still
    # run, but PRD §4.5 budget caps + §9.4 audit cannot be enforced.
    postgres_url: str | None = Field(
        default=None,
        description=(
            "Postgres URL using the asyncpg driver, e.g. "
            "postgresql+asyncpg://openbot:openbot@localhost:5432/openbot. "
            "Required for cost tracking + audit log."
        ),
    )

    # ─── Worker queue (PRD §5.1 / harness spec §9.3) ───
    # Single-process worker with N asyncio consumers. v0.1 defaults to
    # 4 — fine for individual maintainer scale (<10 events/day). At
    # higher load: start more `python -m openbot.queue.runner` processes;
    # they share the same Redis consumer group.
    worker_concurrency: int = Field(
        default=4,
        ge=1,
        le=64,
        description=(
            "Number of asyncio consumer tasks per worker process. "
            "Each task pulls from openbot:workflows independently."
        ),
    )

    debug: bool = Field(default=False, description="Verbose logs; never enable in production.")


@lru_cache
def get_settings() -> Settings:
    """Cached accessor. Tests call `get_settings.cache_clear()` after monkeypatching env."""
    return Settings()
