"""Application config — single source of truth for env vars.

PRD §7: `setup.sh` wizard writes `.env`; this module loads it.
Secrets are wrapped in `SecretStr` so they never leak into logs or repr.
"""

from __future__ import annotations

import ipaddress
import urllib.parse
from functools import lru_cache
from pathlib import Path
from typing import Any

from pydantic import Field, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


def _blank_to_none(value: Any) -> Any:
    """Treat empty / whitespace-only strings as unset.

    Heroku and many cloud env stores cannot distinguish "key absent" from
    "key present but empty"; both surface as ``""``. Default pydantic
    coercion then rejects ``""`` for ``int | None`` / ``Path | None`` fields
    even though the documented intent is "leave it unset for receive-only".
    """
    if isinstance(value, str) and value.strip() == "":
        return None
    return value


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="OPENBOT_",
        extra="ignore",
        frozen=True,
    )

    # ─── GitHub App webhook (PRD §5.1: verify signature is the trust boundary) ───
    github_webhook_secret: SecretStr | None = Field(
        default=None,
        description=(
            "HMAC-SHA-256 secret set when creating the GitHub App. "
            "If unset, /webhook/github responds 503 — webhooks are intentionally "
            "off until the wizard has run."
        ),
    )

    # ─── GitHub App identity (PRD §13 #5: per-user-built App) ───
    # Both must be set for write-back (reply / labels / role) to work.
    # Receive-only deployments (verify + parse only) can leave them unset.
    github_app_id: int | None = Field(
        default=None,
        description="Numeric App ID from the GitHub App settings page.",
    )
    github_app_private_key_path: Path | None = Field(
        default=None,
        description=(
            "Path to the App's PEM-encoded private key. "
            "Generated by `setup.sh`; commonly `./secrets/github-app-private.pem`. "
            "On ephemeral hosts (Heroku/Render) prefer `github_app_private_key_pem`."
        ),
    )
    # Inline PEM source — used on hosts with no persistent filesystem (Heroku,
    # Render, Fly machines without volumes). When both pem and path are set,
    # pem wins so deploys can roll forward without touching the .env path.
    github_app_private_key_pem: SecretStr | None = Field(
        default=None,
        description=(
            "PEM-encoded private key as a literal string (begins with "
            "'-----BEGIN'). Set this in env-var-only deploys (Heroku: "
            '`heroku config:set OPENBOT_GITHUB_APP_PRIVATE_KEY_PEM="$(cat key.pem)"`).'
        ),
    )

    # ─── Persistence ───
    # If unset, webhook dedup falls open (logs WARNING). Production MUST set it.
    redis_url: str | None = Field(
        default=None,
        description=(
            "Redis connection URL, e.g. redis://localhost:6379/0. "
            "Used for webhook dedup (now); rate-limit counters and the "
            "workflow queue land in the middleware slice."
        ),
    )
    # If unset, cost_meter / audit_log are not persisted. LLM workflows still
    # run, but PRD §4.5 budget caps + §9.4 audit cannot be enforced.
    postgres_url: str | None = Field(
        default=None,
        description=(
            "Postgres URL using the asyncpg driver, e.g. "
            "postgresql+asyncpg://openbot:openbot@localhost:5432/openbot. "
            "Required for cost tracking + audit log."
        ),
    )

    # ─── Sandbox (production fix loop — distinct from eval sandbox) ───
    daytona_api_key: SecretStr | None = Field(
        default=None,
        description=(
            "Daytona API key for the production fix-loop sandbox. "
            "Distinct from the eval-suite Daytona key (which is configured "
            "via DAYTONA_API_KEY at the evals/ layer). If unset, the fix "
            "responder fails closed and the use case posts a tailored "
            "comment instead of attempting a fix."
        ),
    )
    daytona_server_url: str | None = Field(
        default=None,
        description=(
            "Override the default Daytona endpoint. Leave unset to use Daytona's public API."
        ),
    )

    # ─── Sandbox snapshot cache (PRD §3 / sandbox-snapshot-cache-plan.md) ───
    # Phase 1 default: OFF. Enable per-feature with
    #   OPENBOT_SANDBOX_CACHE_ENABLED=true
    #   OPENBOT_SANDBOX_CACHE_FEATURES=chat,fix
    sandbox_cache_enabled: bool = Field(
        default=False,
        description=(
            "Enable the sandbox snapshot cache (DaytonaSnapshotCache). "
            "Requires OPENBOT_DAYTONA_API_KEY to be set. Default OFF "
            "(Phase 1 rollout — enable per-feature via "
            "OPENBOT_SANDBOX_CACHE_FEATURES)."
        ),
    )
    sandbox_cache_features: str = Field(
        default="",
        description=(
            "Comma-separated list of features that use the snapshot cache "
            "when sandbox_cache_enabled=True. "
            "Example: 'chat,fix'. Empty string = no features enabled. "
            "Parsed into a set by build_sandbox_cache in openbot.application.sandbox_cache_deps."
        ),
    )
    sandbox_cache_max_entries: int = Field(
        default=50,
        ge=1,
        description="Maximum number of cached snapshots per installation (LRU eviction).",
    )
    sandbox_cache_ttl_seconds: int = Field(
        default=86_400,
        ge=60,
        description="Snapshot age limit in seconds. Entries older than this are treated as miss.",
    )

    # ─── Worker queue (PRD §5.1 / harness spec §9.3) ───
    # Single-process worker with N asyncio consumers. v0.1 defaults to
    # 4 — fine for individual maintainer scale (<10 events/day). At
    # higher load: start more `python -m openbot.entrypoints.worker` processes;
    # they share the same Redis consumer group.
    worker_concurrency: int = Field(
        default=4,
        ge=1,
        le=64,
        description=(
            "Number of asyncio consumer tasks per worker process. "
            "Each task pulls from the openbot:workflows Redis stream independently."
        ),
    )

    debug: bool = Field(default=False, description="Verbose logs; never enable in production.")

    # ─── Debug echo (state-machine slice) ───
    # Routes every classified webhook to the debug echo handler — see
    # ``openbot.application.handlers.debug_echo``. Default ``False`` now that
    # the real workflow path is the intended primary path; operators can still
    # opt back into the debug echo explicitly when tracing the pipeline.
    debug_echo_enabled: bool = Field(
        default=False,
        description=(
            "When True, all classified webhooks are routed to the "
            "debug_echo handler instead of the real workflow stubs. "
            "Useful for verifying the state-machine pipeline end-to-end "
            "before agent logic lands."
        ),
    )

    # ─── Observability ───
    # Sentry is opt-in cross-cutting exception capture. Domain events
    # (workflow STARTED / COMPLETED / SKIPPED) stay in audit_log; Sentry
    # only sees uncaught exceptions and httpx 5xx so the on-call view
    # isn't swamped by routine SKIPPED rows.
    sentry_dsn: SecretStr | None = Field(
        default=None,
        description=(
            "Sentry DSN. When unset, sentry_sdk.init(dsn=None) is a "
            "documented no-op — local dev and CI keep working unchanged."
        ),
    )

    # ─── LLM ───
    # LiteLLM / Anthropic base URL. When set, routes Anthropic model calls
    # to this endpoint (e.g. BigModel GLM proxy). Reads from the standard
    # ANTHROPIC_BASE_URL env var — the same variable langchain_anthropic picks
    # up natively, so a single env var drives both LiteLLM and langchain paths.
    anthropic_api_base: str | None = Field(
        default=None,
        alias="ANTHROPIC_BASE_URL",
        description="Base URL for Anthropic-compatible models (e.g. BigModel GLM proxy).",
    )

    # ─── Sentry ───
    # Tags every Sentry event so prod errors don't mix with dev / preview.
    # Heroku sets this via `heroku config:set OPENBOT_ENVIRONMENT=production`.
    environment: str = Field(
        default="development",
        description="Environment tag attached to Sentry events.",
    )
    # 0.1 = 10% of transactions (standard production starting point).
    # Bump to 1.0 during active debugging or if traffic is very low.
    sentry_traces_sample_rate: float = Field(
        default=0.1,
        ge=0.0,
        le=1.0,
        description="Fraction of transactions sent to Sentry Performance.",
    )
    # Continuous profiling — always-on, low overhead, does not require
    # traces_sample_rate > 0. 1.0 = profile every session (recommended).
    sentry_profile_session_sample_rate: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Fraction of sessions profiled continuously (sentry-sdk 2.24+).",
    )

    # ── Coerce "" → None for optional non-string fields ──
    # Applied at `mode='before'` so it runs ahead of int / Path validation.
    _blank_to_none = field_validator(
        "github_app_id",
        "github_app_private_key_path",
        "redis_url",
        "postgres_url",
        "anthropic_api_base",
        "daytona_server_url",
        mode="before",
    )(staticmethod(_blank_to_none))

    @field_validator("anthropic_api_base", mode="after")
    @classmethod
    def _validate_proxy_url(cls, v: str | None) -> str | None:
        """Reject non-HTTPS and private-network URLs to prevent SSRF.

        ANTHROPIC_BASE_URL is passed directly to litellm as ``api_base``.
        Without validation, any value (file://, internal IPs, cloud metadata
        endpoints) would cause litellm to POST all LLM messages to that host.
        """
        if v is None:
            return v
        parsed = urllib.parse.urlparse(v)
        if parsed.scheme != "https":
            raise ValueError(f"anthropic_api_base must use https://, got scheme={parsed.scheme!r}")
        hostname = parsed.hostname or ""
        try:
            addr = ipaddress.ip_address(hostname)
            if addr.is_private or addr.is_loopback or addr.is_link_local:
                raise ValueError(
                    f"anthropic_api_base must not target a private/loopback address: {hostname}"
                )
        except ValueError as exc:
            # Re-raise our own errors; ignore "not a valid IP" (i.e. hostname).
            if "anthropic_api_base" in str(exc):
                raise
        # Block AWS/GCP/Azure instance metadata hostnames explicitly.
        _blocked = {"169.254.169.254", "metadata.google.internal"}
        if hostname in _blocked:
            raise ValueError(
                f"anthropic_api_base must not target a cloud metadata endpoint: {hostname}"
            )
        return v


@lru_cache
def get_settings() -> Settings:
    """Cached accessor. Tests call `get_settings.cache_clear()` after monkeypatching env."""
    return Settings()
